### ISSUE TITLE
Not working on macOS Sierra

### ISSUE THREAD

**Issue by Richie765** [kevingessner/FunctionFlip#7]
I'm surprised nobody else reported this, not sure if it's just me. Can anybody confirm? Anybody knows of an alternative?

**Comment by kkk777kkk** [comment]
same here, with not finished yet Karabiner for Sierra it is real pain

**Comment by sn0wyfall** [comment]
It works for me! What version are you using?

**Comment by Richie765** [comment]
It seems to be working for me too now.

**Comment by sn0wyfall** [comment]
@kkk777kkk You can install Karabiner beta on macOS Sierra.

**Comment by sn0wyfall** [comment]
@xeroxoid Why don't you just use Karabiner? It contains FunctionFlip's functionality within it.

**Comment by xeroxoid** [comment]
@sn0wyfall Because I do not just want to remap the key I want to flip the functionality (i.e. when pressing the fn key). The problem with Karabiner is that since the new version you can't add modifier keys to function keys, thus in my understanding what I need is not possible.

If you have any insight it would really help though.

Ideally I am looking to remap keys per application i.e. remap the media keys when in chrome (to use them in the Chrome Dev tools)

**Comment by sn0wyfall** [comment]
@xeroxoid I see, you're right. In that case, you could try [Fluor](https://github.com/Pyroh/Fluor). However, it doesn't flip specific function keys. It would flip all of them. To get around that, you could use [BetterTouchTool](https://www.boastr.net) to set F1 to decrease brightness in Chrome/whatever apps, etc.

Actually you could do everything with just BetterTouchTool if you want per-application function flipping. Set the keys to F1, F2, etc. in system prefs and then remap them globally to the media keys in BTT, and then in each individual application you can change them to whatever you want. You could download the trial to test it out.

**Comment by xeroxoid** [comment]
Thanks excellent! I have already purchased BetterTouchTool and am using it to customize mouse plus the making use of window snapping features. 

I had tried to do that but I thought that single function keys could not be assigned as shortcuts in BTT, but by setting the default to be the Fx keys from the OSX keyboard preferences it does indeed work.

No need for any other app if you have BetterTouchTool!

**Comment by sn0wyfall** [comment]
@xeroxoid Oh, nice, woohoo! Glad you got that working :)

**Comment by kevingessner** [comment]
Not reproducible here -- FunctionFlip 2.2.3 works fine on 10.12.6.

**Comment by fleish** [comment]
I was having similar problems in Sierra. I eventually got it working and suspect it has to do with [Gatekeeper](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/). I don't recommend enabling apps from anywhere permanently, nor did I find it was strictly required to get FunctionFlip working again. But I did find that I needed to go into System Preferences -> Security & Privacy after installing the FF preference pane and click "open anyway" next to the exception it had flagged for trying to install an app from an unknown source.

I'm glad this app is still working. Death to Launchpad Long live Dashboard!

**Comment by fleish** [comment]
UPDATE: on at least one of my machines the functionality does seem to keep reverting back. I've reinstalled & re-configured functionflip & the accessibility settings several times but after a period of time I find I have to do fn+F4 for dashboard to show up instead of Launchpad. I'm not sure what is triggering this as I haven't noticed any patterns that result in the behavior. Just that it will work for a while and then stop working.
